// automatically generated by the FlatBuffers compiler, do not modify

package me.gm.cleaner.schema.pathtree

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DirectoryNode : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DirectoryNode {
        __init(_i, _bb)
        return this
    }
    val name : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val size : Long
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val lastModifiedTime : Long
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val lastAccessTime : Long
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val creationTime : Long
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    fun files(j: Int) : me.gm.cleaner.schema.pathtree.FileNode? = files(me.gm.cleaner.schema.pathtree.FileNode(), j)
    fun files(obj: me.gm.cleaner.schema.pathtree.FileNode, j: Int) : me.gm.cleaner.schema.pathtree.FileNode? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val filesLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    fun dirs(j: Int) : me.gm.cleaner.schema.pathtree.DirectoryNode? = dirs(me.gm.cleaner.schema.pathtree.DirectoryNode(), j)
    fun dirs(obj: me.gm.cleaner.schema.pathtree.DirectoryNode, j: Int) : me.gm.cleaner.schema.pathtree.DirectoryNode? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val dirsLength : Int
        get() {
            val o = __offset(16); return if (o != 0) __vector_len(o) else 0
        }
    val fileCount : Long
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val dirCount : Long
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_5_26()
        fun getRootAsDirectoryNode(_bb: ByteBuffer): DirectoryNode = getRootAsDirectoryNode(_bb, DirectoryNode())
        fun getRootAsDirectoryNode(_bb: ByteBuffer, obj: DirectoryNode): DirectoryNode {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDirectoryNode(builder: FlatBufferBuilder, nameOffset: Int, size: Long, lastModifiedTime: Long, lastAccessTime: Long, creationTime: Long, filesOffset: Int, dirsOffset: Int, fileCount: Long, dirCount: Long) : Int {
            builder.startTable(9)
            addDirCount(builder, dirCount)
            addFileCount(builder, fileCount)
            addCreationTime(builder, creationTime)
            addLastAccessTime(builder, lastAccessTime)
            addLastModifiedTime(builder, lastModifiedTime)
            addSize(builder, size)
            addDirs(builder, dirsOffset)
            addFiles(builder, filesOffset)
            addName(builder, nameOffset)
            return endDirectoryNode(builder)
        }
        fun startDirectoryNode(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(0, name, 0)
        fun addSize(builder: FlatBufferBuilder, size: Long) = builder.addLong(1, size, 0L)
        fun addLastModifiedTime(builder: FlatBufferBuilder, lastModifiedTime: Long) = builder.addLong(2, lastModifiedTime, 0L)
        fun addLastAccessTime(builder: FlatBufferBuilder, lastAccessTime: Long) = builder.addLong(3, lastAccessTime, 0L)
        fun addCreationTime(builder: FlatBufferBuilder, creationTime: Long) = builder.addLong(4, creationTime, 0L)
        fun addFiles(builder: FlatBufferBuilder, files: Int) = builder.addOffset(5, files, 0)
        fun createFilesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startFilesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDirs(builder: FlatBufferBuilder, dirs: Int) = builder.addOffset(6, dirs, 0)
        fun createDirsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDirsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addFileCount(builder: FlatBufferBuilder, fileCount: Long) = builder.addLong(7, fileCount, 0L)
        fun addDirCount(builder: FlatBufferBuilder, dirCount: Long) = builder.addLong(8, dirCount, 0L)
        fun endDirectoryNode(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
